project_id = "sngjqizvseyvuaxfvvjr"

[functions.bootstrap-ceo]
verify_jwt = false

[functions.create-employee]
verify_jwt = false

[functions.reset-hr]
verify_jwt = false

[functions.lookup-username]
verify_jwt = false