// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sngjqizvseyvuaxfvvjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZ2pxaXp2c2V5dnVheGZ2dmpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1OTkzOTUsImV4cCI6MjA3NDE3NTM5NX0.YeBhmzlHa0OXG5vObGcqXldCF6yY1ev3O_CemTv85so";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});